spring:
  application:
    name: jobmanagement
  datasource:
    initialization-mode: embedded
    url: jdbc:h2:mem:test
    username: sa
  h2:
    console:
      enabled: true
      path: /h2_console
      settings:
        web-allow-others: true
  jpa:
    generate-ddl: true
    database: h2
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: false
